### ISSUE TITLE
Ошибка при запуске/при нажатии на любую кнопку

### ISSUE THREAD

**Issue by MickeyShide** [gurux13/chrome-audio-delay#1]
Ниже текст ошибки

**Comment by MickeyShide** [comment]
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Configurator.SystemHelper.GetAudioEndpointDelays() in D:\a\chrome-audio-delay\chrome-audio-delay\Configurator\SystemHelper.cs:line 37
   at Configurator.MainForm.btnRefresh_Click(Object sender, EventArgs e) in D:\a\chrome-audio-delay\chrome-audio-delay\Configurator\MainForm.cs:line 136
   at Configurator.MainForm.Form1_Load(Object sender, EventArgs e) in D:\a\chrome-audio-delay\chrome-audio-delay\Configurator\MainForm.cs:line 149
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
System.Private.CoreLib
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.CoreLib.dll
----------------------------------------
Configurator
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase (база кода): file:///C:/ChromeAudioPatcher/Configurator.dll
----------------------------------------
System.Runtime
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.422.16407
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.422.16407
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.422.16404
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.422.16407
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Runtime.Loader
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.422.16407
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/ru/System.Windows.Forms.resources.dll
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.422.16404
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Memory.dll
----------------------------------------
System.Drawing
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.422.16407
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ObjectModel.dll
----------------------------------------
System.Linq
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Linq.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.422.16404
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.NonGeneric.dll
----------------------------------------
CoreAudio
    Версия сборки: 2021.9.1.37
    Версия Win32: 2021.9.1.37
    CodeBase (база кода): file:///C:/ChromeAudioPatcher/CoreAudio.dll
----------------------------------------
netstandard
    Версия сборки: 2.1.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/netstandard.dll
----------------------------------------
System.Diagnostics.Process
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.Process.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Версия сборки: 2.10.1.0
    Версия Win32: 2.10.1.0
    CodeBase (база кода): file:///C:/ChromeAudioPatcher/Microsoft.Win32.TaskScheduler.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Xml.ReaderWriter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.RegularExpressions.dll
----------------------------------------
System.Security.Principal.Windows
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Claims.dll
----------------------------------------
Microsoft.Win32.Registry
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/Microsoft.Win32.Registry.dll
----------------------------------------
System.Private.Uri
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.522.21309
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Immutable.dll
----------------------------------------

************** Оперативная отладка (JIT) **************

**Comment by gurux13** [comment]
Тестирование хромает.
Спасибо, теперь должно работать.
