### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by mttthew** [gurux13/chrome-audio-delay#3]
Haven't been able to get Configurator to work for the last week or two - any idea why this may be? Program loads fine but doesn't seen to have an effect on audio delay anymore. Tried both Chrome and Edge, tried restarting browsers, redownloading Configurator, etc. Any help would be appreciated as this program had been a lifesaver for me before it stopped working!

**Comment by gurux13** [comment]
Any chance the dll or the binary gets deleted by an antivirus?

If not, can you please get logs from DebugView and attach here?

**Comment by mttthew** [comment]
[debugview.LOG](https://github.com/gurux13/chrome-audio-delay/files/15053313/debugview.LOG)

I'm a bit clueless about this kind of thing, so I don't know how to check the dll/binary, but here's a log of me starting the program and then restarting Chrome, if that helps. If there's anything else I can do, let me know - really appreciate the help.

**Comment by gurux13** [comment]
Interesting, there is nothing in the logs at all. Did you enable Capture -> Capture global win32 (need to run as admin for that)?
Also, did you use the latest version of this app?

Please do the following:
1. Check that the program folder contains `Configurator.exe`, `ManualInject.exe` and `InjectedDll.dll`. If any of these files is missing, please disable your antivirus and redownload the program. Add the folder in your antivirus exceptions folder.
2. If the above didn't help, run dbgview as administrator, and enable `Capture -> Capture global win32`
3. Open Chrome
4. Enter `chrome://restart` in the address bar, hit Enter
5. Once chrome reopens, open something that plays music (such as a youtube video)
6. Stop capture in dbgview (press the magnifying glass icon)
7. Save the debug log
8. Check that there is nothing confidential in the log
9. Upload the log here.

Thank you!

**Comment by mttthew** [comment]
Problem solved! InjectedDll.dll was missing - followed the instructions in point 1 and it solved the issue. Thank you so much for your help, really appreciate it!
