### ISSUE TITLE
The compatibility for browser on Windows 11 ARM.

### ISSUE THREAD

**Issue by i1itione** [gurux13/chrome-audio-delay#5]
I use Parallels Desktop for running Windows 11 ARM on my Macbook Air M1, and I got these two results when trying chrome-audio-delay:
1. It works on browser of x64 version.
2. It doesn't work on browser of ARM64 version.

**Comment by gurux13** [comment]
Unfortunately, ARM64 is not supported. This is closely tied to the machine code and the library linkage of AMD64, supporting ARM64 would mean developing it almost from scratch.
Since I do not have any non-mobile ARM64 devices, this is not feasible :(
